name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    environment: Continuous Integration
    strategy:
      matrix:
        emacs_version:
          # Add more lines like this if you want to test on different Emacs versions.
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
    steps:
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Byte-compile the project
      run: |
        eldev -dtT compile --warnings-as-errors

    - name: Lint the project
      run: |
        eldev -p -dtT lint

    - name: Test the project
      # We don't set up the env variables so no integration tests will be run
      run: |
        eldev -p -dtT test
  integration-tests:
    runs-on: ubuntu-latest
    environment: Continuous Integration
    steps:
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: 29.4

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Test the project
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
        # I can't seem to get Gemini to stop rate limiting me, temporarily disabling.
        # GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      run: |
        eldev -p -dtT test
